[package]
name = "pacrun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo-types = "0.7.9"
osm-xml = { version = "0.6.2", path = "../osm-xml" }
serde-xml-rs = "0.6.0"
serde_json = "1.0.95"
